# Generated by Django 3.1.2 on 2020-11-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettershuffle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='bio_url',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='details',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
