# Generated by Django 3.1.2 on 2020-11-01 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lettershuffle', '0002_auto_20201031_1934'),
        ('user', '0002_auto_20201031_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='accessed',
            new_name='accessed_problems',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='attempts',
            new_name='attempted_problems',
        ),
        migrations.AlterField(
            model_name='access',
            name='accessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='access',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='lettershuffle.puzzle'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='attempter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lettershuffle.puzzle'),
        ),
    ]
