# Generated by Django 3.1.2 on 2020-10-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201026_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='last_edit_time',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
