# Generated by Django 3.1.2 on 2020-10-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201019_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
