# Generated by Django 3.1.2 on 2020-10-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201019_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
